def build(bld):
    kw = {}
    kw["features"] = ["cxx", "cxxprogram", "debug-info"]
    kw["source"] = [
        "main.cpp",
        "test_gobject.cpp",
        "test_gthread.cpp",
        "test_gtimer.cpp",
        "test_defect_regressions.cpp"
    ]
    kw["includes"] = ["."]
    kw["use"] = ["GQT", "gtest"]

    bld(target='Tests', **kw)
