def build(bld):
    kw = {}
    kw["source"] = [
        "GThread.cpp",
        "GObject.cpp",
        "GCoreApplication.cpp",
        "GAbstractEventDispatcher.cpp",
        "GEventDispatcherDefault.cpp",
        "GEventDispatcherWin32.cpp",
        "GEventDispatcherLinux.cpp",
        "GTimer.cpp"
    ]
    kw["includes"] = ["."]
    kw["export_includes"] = ["."]
    kw["use"] = ["boost"]
    bld(target='GQT', features='cxx', **kw)