def build(bld):
    kw = {}
    kw["includes"] = ["."]
    kw["export_includes"] = ["."]
    kw["use"] = ["boost"]
    kw["features"] = ["cxx", "debug-info"]

    kw["source"] = [
        "AbstractEventDispatcher.cpp",
        "CoreApplication.cpp",
        "EventDispatcherDefault.cpp",
        "Object.cpp",
        "Thread.cpp",
        "ThreadData.cpp",
        "Timer.cpp",
    ]

    if bld.env.DEST_OS == "win32":
        kw["source"] += [
            "EventDispatcherWin32.cpp",
            "ThreadWin.cpp",
        ]
    elif bld.env.DEST_OS == "linux":
        kw["source"] += [
            "EventDispatcherLinux.cpp",
            "ThreadPosix.cpp",
        ]

    bld(target="QtLikeSignal", **kw)

    bld.recurse("tests")
